# fly.toml app configuration file generated for empty-cloud-2654 on 2023-09-20T11:21:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-cloud-2654"
primary_region = "bos"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
