###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNsaW5reVBvdGF0byIsImlkIjoiNjUxYzQzNDNmMDRjZDE4ZWVmOGE4ZmI2IiwiaWF0IjoxNjk2NjIwNDk4LCJleHAiOjE2OTY2MjQwOTh9.DN1GR1eizqz8Os53fXw0EuNj62UnkYBVZlwsMKh4pRk
Content-Type: application/json

{
  "title": "A Blog",
  "author": "Brian Patino",
  "url": "http://localhost:8080",
  "likes": 3
}

###
DELETE http://localhost:3001/api/blogs/651c48b5270cca7f5d3290f1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNsaW5reVBvdGF0byIsImlkIjoiNjUxYzQzNDNmMDRjZDE4ZWVmOGE4ZmI2IiwiaWF0IjoxNjk2MzczNzExLCJleHAiOjE2OTYzNzczMTF9.XLWZiYcTVMK4pnGk8eGoTEi6rM5gxUTw9wfQklakjTg

###
PATCH http://localhost:3001/api/blogs/5a7d1b4b1c9d440000b7e8b1
Content-Type: application/json

{
  "likes": null
}
