###
GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNsaW5reVBvdGF0byIsImlkIjoiNjUxYzQzNDNmMDRjZDE4ZWVmOGE4ZmI2IiwiaWF0IjoxNjk2NjIwNDk4LCJleHAiOjE2OTY2MjQwOTh9.DN1GR1eizqz8Os53fXw0EuNj62UnkYBVZlwsMKh4pRk
Content-Type: application/json

{
  "title": "A Blog",
  "author": "Brian Patino",
  "url": "http://localhost:8080",
  "likes": 3
}

###
DELETE http://localhost:3001/api/blogs/6526da1074884ee94d99812e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNsaW5reVBvdGF0byIsImlkIjoiNjUxYzQzNDNmMDRjZDE4ZWVmOGE4ZmI2IiwiaWF0IjoxNjk3NzM5NTUyLCJleHAiOjE2OTc3NDMxNTJ9.FsR16KVGm5lvbLCFWdvlMBScGLT0Za8pr9XJZAy2utw

###
PATCH http://localhost:3001/api/blogs/652c7f337e7ad1b689810ef0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNsaW5reVBvdGF0byIsImlkIjoiNjUxYzQzNDNmMDRjZDE4ZWVmOGE4ZmI2IiwiaWF0IjoxNjk3NDE0MTk3LCJleHAiOjE2OTc0MTc3OTd9.OH5RxXCJen46ajGgd6ZyWfi8TgaqmNkM8u9XvPoAcrM
Content-Type: application/json

{
  "likes": 3,
  "user": {
    "username": "SlinkyPotato",
    "name": "Brian Patino",
    "id": "651c4343f04cd18eef8a8fb6"
  }
}
