### 
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/650c309e44dc36d0d71796ca

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/someInvalidId

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Brian Patino",
  "number": "123-456-7777"
}

###
PUT http://localhost:3001/api/persons/0039227318279e66325f3f50
Content-Type: application/json

{
  "name": "Brian Patino",
  "number": "000000"
}

###
GET http://localhost:3001/api/test
